@echo off
echo booting up...
echo finding nessaccary files...
echo loading chat.py...
echo loading  e1#-os...
echo just a lil bit...
echo not long now...
echo done...
echo press any key to boot