a="the epic guy walked home from mcdonalds"
import time
x=20
def epic():
 print(x)
 time.sleep(0.25)
 print(x-1)
 time.sleep(0.5)
 print(x-2)
 time.sleep(0.8)
 print(x-3)
 time.sleep(1)
 print(x-4)
 time.sleep(1)
 print(x-5)
 time.sleep(1)
 print(x-6)
 time.sleep(1)
 print(x-7)
 time.sleep(1)
 print(x-8)
 time.sleep(1)
 print(x-9)
 time.sleep(1)
 print(x-10)
 time.sleep(1)
 print(x-11)
 time.sleep(1)
 print(x-12)
 time.sleep(1)
 print(x-13)
 time.sleep(1)
 print(x-14)
 time.sleep(1)
 print(x-15)
 time.sleep(1)
 print(x-16)
 time.sleep(1)
 print(x-17)
 time.sleep(1)
 print(x-18)
 time.sleep(1)
 print(x-19)
 print(a)
 print(input())
epic()
print("ok you have  epic wpm")